# yha pr hm apne mongoDB server ki ip , port , aur database ka naam likhte h
# connection banane ke liye . bs enta likhate hi spring boot application connection
# bna lega mongoDb se jo hmare system pe h

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Journaldb
#spring.data.mongodb.username=xyz  --> username aur password set hoga tb denge esko
#spring.data.mongodb.password=abc
