# yha pr hm apne mongoDB server ki ip , port , aur database ka naam likhte h
# connection banane ke liye . bs enta likhate hi spring boot application connection
# bna lega mongoDb se jo hmare system pe h

# ye locally store krta tha data ko ,mere system pe
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

# ye aws ke server pr store kr rha h data ko
spring.data.mongodb.uri = mongodb+srv://tripathijiaditya108_db_user:EiqTVLa5mHL1On4W@cluster0.hkhukvn.mongodb.net/?appName=Cluster0


spring.data.mongodb.database=Journaldb
#spring.data.mongodb.username=xyz  --> username aur password set hoga tb denge esko
#spring.data.mongodb.password=abc
spring.data.mongodb.auto-index-creation=true